### PR TITLE
Construct "save as" filename from video title if possible

### PR DESCRIPTION
**Pull request by lgedgar**
This is in regard to https://github.com/orgs/Qortal/projects/4/views/2?pane=issue&itemId=49345455

Let me know if I need to do anything further than make this PR?  Happy to answer any questions etc.

### CODE REVIEW

**Comment by lgedgar** [comment]
Before I forget..may need to "filter" the title somehow in case of certain special chars?  I realize certain chars are not allowed in title when publishing normally, but that doesn't mean they can't get in there by some other crafty means.  But not sure off-hand what chars would need to be avoided for saving a local file.  So..reminder to self, to check later..

**Comment by QortalSeth** [comment]
You do need to filter the filename because there are some characters that titles allow that Windows and other Operating Systems won't allow in filenames. These characters include \ / : * ? " < > | 

To fix this, add the following variable to src/constants/Misc.ts:  
export const titleFormatterOnSave = /[^a-zA-Z0-9\s-_!()&',.;—~@#$%^+=]/g;

Then where you make the variable that has the title to save, set it to something like:
const formattedTitle = varName.replace(titleSaveFormatter, "")

This will remove any characters that shouldn't be used from the title

**Comment by lgedgar** [comment]
Thanks.  I started to implement that filter but in order to test, I hard-coded a sample filename of:

    [stuff] and-things? and/or *caveats.mp4

just so I could confirm the filter behavior.  But also I wanted to see what would happen with that filename before I added the filter.  And it turns out the browser will automatically handle stripping bad chars.  This was the case in a "conventional" browser (Firefox), as well as within the Qortal UI dev mode.  In both cases it saved okay:

- Firefox: `[stuff] and-things and_or caveats.mp4`
- Qortal UI: `[stuff] and-things_ and_or _caveats.mp4`

So I kinda lean toward leaving the filter out unless we discover an actual problem.  I trust the browsers know better than we do, which chars are (not) safe.  Thoughts?

**Comment by QortalSeth** [comment]
> Thanks. I started to implement that filter but in order to test, I hard-coded a sample filename of:
> 
> ```
> [stuff] and-things? and/or *caveats.mp4
> ```
> 
> just so I could confirm the filter behavior. But also I wanted to see what would happen with that filename before I added the filter. And it turns out the browser will automatically handle stripping bad chars. This was the case in a "conventional" browser (Firefox), as well as within the Qortal UI dev mode. In both cases it saved okay:
> 
>     * Firefox: `[stuff] and-things and_or caveats.mp4`
> 
>     * Qortal UI: `[stuff] and-things_ and_or _caveats.mp4`
> 
> 
> So I kinda lean toward leaving the filter out unless we discover an actual problem. I trust the browsers know better than we do, which chars are (not) safe. Thoughts?

Interesting, I didn't know that. Very well then, I'll test your code as is and if it works it will be accepted.

**Pull request merged**
